// <auto-generated />
using DestinyBuildsBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DestinyBuildsBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DestinyBuildsBack.Models.Arma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Armas");
                });

            modelBuilder.Entity("DestinyBuildsBack.Models.ArmaduraExotica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.ToTable("ArmadurasExoticas");
                });

            modelBuilder.Entity("DestinyBuildsBack.Models.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmaPrincipalId")
                        .HasColumnType("int");

                    b.Property<int>("ArmaSecundariaId")
                        .HasColumnType("int");

                    b.Property<int>("ArmaTerciariaId")
                        .HasColumnType("int");

                    b.Property<int>("ArmaduraExoticaId")
                        .HasColumnType("int");

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<string>("Mods")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubclaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArmaPrincipalId");

                    b.HasIndex("ArmaSecundariaId");

                    b.HasIndex("ArmaTerciariaId");

                    b.HasIndex("ArmaduraExoticaId");

                    b.HasIndex("ClaseId");

                    b.HasIndex("SubclaseId");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("DestinyBuildsBack.Models.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clases");
                });

            modelBuilder.Entity("DestinyBuildsBack.Models.Subclase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.ToTable("Subclases");
                });

            modelBuilder.Entity("DestinyBuildsBack.Models.ArmaduraExotica", b =>
                {
                    b.HasOne("DestinyBuildsBack.Models.Clase", "Clase")
                        .WithMany()
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("DestinyBuildsBack.Models.Build", b =>
                {
                    b.HasOne("DestinyBuildsBack.Models.Arma", "ArmaPrincipal")
                        .WithMany()
                        .HasForeignKey("ArmaPrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DestinyBuildsBack.Models.Arma", "ArmaSecundaria")
                        .WithMany()
                        .HasForeignKey("ArmaSecundariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DestinyBuildsBack.Models.Arma", "ArmaTerciaria")
                        .WithMany()
                        .HasForeignKey("ArmaTerciariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DestinyBuildsBack.Models.ArmaduraExotica", "ArmaduraExotica")
                        .WithMany()
                        .HasForeignKey("ArmaduraExoticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DestinyBuildsBack.Models.Clase", "Clase")
                        .WithMany()
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DestinyBuildsBack.Models.Subclase", "Subclase")
                        .WithMany()
                        .HasForeignKey("SubclaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArmaPrincipal");

                    b.Navigation("ArmaSecundaria");

                    b.Navigation("ArmaTerciaria");

                    b.Navigation("ArmaduraExotica");

                    b.Navigation("Clase");

                    b.Navigation("Subclase");
                });

            modelBuilder.Entity("DestinyBuildsBack.Models.Subclase", b =>
                {
                    b.HasOne("DestinyBuildsBack.Models.Clase", "Clase")
                        .WithMany()
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");
                });
#pragma warning restore 612, 618
        }
    }
}
